version: "3.8"

services:
  mysql:
    image: mysql:8.0
    command:
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_general_ci"
      - "--skip-log-bin"
      - "--default-authentication-plugin=mysql_native_password"
    environment:
      - MYSQL_ROOT_PASSWORD=labpass
      - MYSQL_DATABASE=puny
      - MYSQL_USER=lab
      - MYSQL_PASSWORD=labpass
    ports:
      - "3307:3306"
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

